language: java
jdk:
- oraclejdk8
before_script:
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
script:
- "./gradlew postRequest"
after_success:
- bash changelog.sh
env:
  global:
    secure: V+b4wGZIbduxZ/dtfSGvJYVlJoOefz02oCrz95kqAfzFv0JbZFei49Zc46niLV5LL6fx0koIyXx7mp0/U/lZIxp/juR3eEbSWKzM8HYLykpObIGusYMLwH7nfkPdfmmC6PGs9jtC56D1Y5FByiaXl0LIw9IDpqBU7C5a2GPM+foU5cgaG4Pc5NeNbkMcD/0kF3lIoZ+NxIZEvibpdlrdm25+0DdrpxZmEbrULJrxQjG8nO5A04G7TMMmTZRViKRhTbELQvn03aVQGE47rqaBWAxWDDlwqcp/KFiTMytXw4vVSyje9PHBdLQc9bV01N+HHDfPoU3FUJ376gX5Ta4L6aP/m8InXCTv8nhXVfX7fSyMO5q0Ip1uk0SFMRBG3ShL5/s9twlubiUDof4xKZccSKOjpRMAj9wFDfgVjbGY4oDTjBrtlHe6uQQkn0Jeoj7WfA7yeeQFja67pm189SCArrAbk2Vqjzdkc8YOdM4DP65m1XdG8HxDayyxxfGNYOk9f19kHNmnBnF9zoKlFafCicv5eD+2u3rlDX3jaaO6/WJUsKPrF09pM/5LehVj5MFzaqVgalq+zkIGMpYKXn4mwYvQgXNlv3YL/khIxu98us/BO2tYZ7F10XC/Es3vJlgB61XmMDiycg2V53glRY8Z/FICxHpX1juPhMWsd9tSdf4=
    secure: JhFETxhYsUtmKBZhGah8V3CZ2mtOCvPsXNjzTB6zF+3c5f2cwUmncHoRWY3mXvpnhEJTpUmVA6el4cwLRQPNaihUmg8jQRsuTG/Y9R0VF+lyX/H8YSHKy3pJbpz16RufKy5mQRlAeCjvdQ1CbuB2knK+N2YxpUrGOuciLlxjkjIrlNtQlCqhPxibWMXIbUS3NbDa7G1Q0zML7YCYgGMM0nDq/tHQBIN0VM4eD8ns191kXFOgj/mqpZS2Q5pELUK7jsbll0LDtV3qX12RmLjH4zAUaUNRQVrr0XLX3XzIc19MgI6ILQ5pObH0IN+8tsPYTBJEnNkCjVz9Jq1tcPEB2M5IkdmiLmRMDrTQXbi4bPx+UDgjlA75XZPbKBTbki2EuHDKpzhgIsDWUrp5s5K18/pfeAMtzp972J9vmnxfbHW/eqD1rV0fLnVDb5/Vu7XrBZHVFBMeBcZoGL/8YtmIcX/fZxZ9C5+UKWhlyhf4VnXtyCfQ4tJDtr1Ng8hee5dtgVK8//EPpW5B5RUzxSvaAoEIPzpJ06rdODo+aqA/iuNF6iDuY4n1R0z1aAj/DLOHHXpbHCaRe+7CV2+pQi0eE5SbyjdgrFM38L2plod5eRDcIi516NI0+/apYEVej1zrKpQIUSDG7hYOV5lemrIXqjyAp+N7yxpRkzTHxADadec=
