language: java
jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "dumb-code"
    token:
      secure: S7c36a6JOsaktShBFS+P3VeR0JETMZdK1KOI6zsp8tOY/eOjV9EdmNc1RxOyOn9GjAb1Jf2/QuoacaMz4wQinYqntyUD31oUctR1wXyVFYtDxA3yF1WDhazIGo/HG6NlklwJcomS93E9s5pezNzEdwxCgNW8cex49rA0NBc1kym1w0y+Fh5y6OzEHQ4c+ctwj2mhR0hKO73eItBSMZfoBmHMzNsd93//JxIIDcI3h0/axLecoLN8Mug8efke3SBsRhTCPJhWHbprqglVqVI5NGKO/IJ9xnEN5+sWWbbQzqZZ+fnN1EU+BelRjYTo8GbPm8lVnF3/ArkJBab1p0aLUa7dJsOGqsNQsI1fW1zGysTMuNbqXPpauRMtQwbbHm7iuYtx4q5cS+DRoHZe44ebp4kIDbuCIhCOvtVLB+whQ8aL3pz7iozqKvtbkUP8ZhfHVTTnqQlk5Dydvd6ie7SyWLj2zucKHcIGFR+x80MGndOiUs0OdfEatjoe7iWMp2I2M5IOncYMbviATrbv29344XksASgG2MMo4q83nLJI2KX6sy0UJBLcrAw5J1VJYi2wncJ1B5qCYEYe9qrtoptQTYpPZuoKpWK/8J4eGC7+oE4F0/LrSVo8+L6zpgqIesH2J8FWMHKgyVCaz34c1TToWq6C7UwhOiciay2mHJDI0N4=

before_script:
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- export COMMITTER_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
- export COMMIT_HASH="$(echo $TRAVIS_COMMIT | cut -c1-7)"
install:
  - true
script:
- sonar-scanner
- "./gradlew postRequest"
after_script:
  - bash changelog.sh
after_failure:
  "./gradlew notifyIfError"
env:
  global:
  - secure: JhFETxhYsUtmKBZhGah8V3CZ2mtOCvPsXNjzTB6zF+3c5f2cwUmncHoRWY3mXvpnhEJTpUmVA6el4cwLRQPNaihUmg8jQRsuTG/Y9R0VF+lyX/H8YSHKy3pJbpz16RufKy5mQRlAeCjvdQ1CbuB2knK+N2YxpUrGOuciLlxjkjIrlNtQlCqhPxibWMXIbUS3NbDa7G1Q0zML7YCYgGMM0nDq/tHQBIN0VM4eD8ns191kXFOgj/mqpZS2Q5pELUK7jsbll0LDtV3qX12RmLjH4zAUaUNRQVrr0XLX3XzIc19MgI6ILQ5pObH0IN+8tsPYTBJEnNkCjVz9Jq1tcPEB2M5IkdmiLmRMDrTQXbi4bPx+UDgjlA75XZPbKBTbki2EuHDKpzhgIsDWUrp5s5K18/pfeAMtzp972J9vmnxfbHW/eqD1rV0fLnVDb5/Vu7XrBZHVFBMeBcZoGL/8YtmIcX/fZxZ9C5+UKWhlyhf4VnXtyCfQ4tJDtr1Ng8hee5dtgVK8//EPpW5B5RUzxSvaAoEIPzpJ06rdODo+aqA/iuNF6iDuY4n1R0z1aAj/DLOHHXpbHCaRe+7CV2+pQi0eE5SbyjdgrFM38L2plod5eRDcIi516NI0+/apYEVej1zrKpQIUSDG7hYOV5lemrIXqjyAp+N7yxpRkzTHxADadec=
  - secure: xY5VAor7ADnq9frMY5WHbQKk308l06h2RVzOSx2tl5ziUnv+xgrg6DEUsoPmdD+ISqBOGxqMz4w4UPy0FEpQ1YXiq2RMEotzv8XrjSqLQkxb5ChPX00o9cH5FnwPhIFxyYKD2pBGYUdnbivfc0yAcN3Q2fwjKAH8Rb0X263BhUVNXZXGTWX2a8axb8/eb4SzjF2ZrUARP1+3FyEJ6nAisa2scCOx8MzHGetlc1XWvHmfNjPSvmIUIPEEpJdpcdcP2TnL1ty7FulvBjBtH90wEH2Tg0Yj5l2g2brQa83uJlD7jpiGS7uHF235EUmTLJxA1/DCI4P6e89AbQExbQPoClnFuq1g32S/g58QhhjYY656dZ5ZW244xb0jIh2akl/mt7upiiXvqWI7ctEVC7VcsidY5barapvznhSQjsHxxeqlhobMeBQ6bbF6aM1PE2LGsXHtV26COO5SjzZ/eLOAk+U3XiMvahRyokt32y1WnabGIbdMu6GypJV6SW5beQ0ae96gZsiC3U/LI79D37uHnSiI+BswgzJ3CukbPZWJCm0cKf9c13VvAMUVy3dto/01K2vXD9uk9Z46lLGXOyI4hMnMnUl46/rDkCO5AP3eBRYOTi+gqqotJeQj4wzH6NJiPyvj//Ja0FP5uZ/+kJzHv0savYJP+Kqx9VCvXSEhN+s=
