modLoader="javafml"
loaderVersion="[28,)"
license="All right reserved"
[[mods]]
modId="dumblibraray"
version="${file.jarVersion}"
displayName="Dumb Library"
authors="Wyn Price"
description='''Library'''