modLoader="javafml"
loaderVersion="[36,)"
license="All right reserved"
[[mods]]
modId="dumblibrary"
version="${file.jarVersion}"
displayName="Dumb Library"
authors="Wyn Price"
description='''Library'''