# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "1.16" ]
  pull_request:
    branches: [ "1.16" ]
  workflow_dispatch:

jobs:
  Test-And-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Create Server EULA
        run: |
          mkdir run
          echo "eula=true" > run/eula.txt
      - name: Dummy Run Server Until World Tick
        run: ./gradlew runServer
      - name: Test for crashes
        run: |
          if [ -d "run/crash-reports" ]; then
            exit 9999
          fi